### ISSUE TITLE
🆕 Software Suggestion | Odysee / LBRY (Video/Audio Platforms)

### ISSUE THREAD

**Issue by lrq3000** [privacytools/privacytools.io#2332]
## Basic Information

**Name:** Odysee (LBRY protocol)
**Category:** Video/Audio Platforms
**URL:** https://odysee.com/ (source code: https://github.com/lbryio/lbry-desktop/tree/odysee - see here for [an explanation](https://www.reddit.com/r/lbry/comments/k395yw/where_can_i_find_odysee_source_code/))

## Description

Odysee is a web front-end to the LBRY protocol, a blockchain incentivized IPFS distributed network for video streaming, with comments and votes. The censorship-resistant LBRY protocol allows to share any kind of file type, but Odysee is restricted to video for the moment. Users earn $LBC tokens from various activities such as watching videos, and can tip or buy content with it.

## Why I am making the suggestion

It is the only fully open-source distributed video streaming service, all the others are at least partially closed source. It is a now well-established alternative to Peertube, it has good streaming performances and features (auto encoding in various resolutions has been implemented lately, as well as voting).

It was already discussed as part of issue #1252 which was accepted, but LBRY was not added on PTIO, so this issue will serve as a confirmation or rejection.

## My connection with the software

None, I just use it from time to time.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
I'm still against adding LBRY, however I'd be interested to hear your thoughts @privacytools/editorial

**Comment by lrq3000** [comment]
@freddy-m May I ask why you are against? I didn't find your comments in the discussion I linked above but maybe I missed another one? I have studied in-depth how the LBRY ecosystem works so I can maybe clarify things :-)

**Comment by freddy-m** [comment]
I'm very sceptical of any technology marketed using blockchain, though I am very happy to change my mind on the matter...

**Comment by lrq3000** [comment]
You're right to be skeptical, most projects using blockchains don't in fact provide any real innovation in terms of privacy ;-)

In the case of LBRY, the blockchain plays only one primary role: to be a DNS pointing to where the content is (it also stores some authorship metadata). It's simply using IPFS to store these records. Then the video content is shared P2P, and the first to share is either the LBRY/Odysee platform if the content is not illegal, or if it is censored then it can be streamed from the author's computer.

So let's say that it's similar to PeerTube (which also uses a P2P delivering system), with the difference that the records allowing to find the videos are not stored on instance servers but on the blockchain, so the records are uncensorable. But the video content is, and the author can be tracked down since it's served P2P.

PeerTube can be self-hosted, potentially even as a Tor hidden service, which allows to protect content authors since then it's the instance server that serves the content.
For LBRY/Odysee, I am not aware of such a system in case the video gets censored, I wonder if it's possible to serve video content through self-contained networks such as Tor. I don't think someone did that yet but I can't see why it wouldn't be possible.

**Comment by lrq3000** [comment]
I've found these pertinent issues:
* https://github.com/lbryio/lbry-sdk/issues/3235
* Data seems to be fully encrypted except for wallet calls but maybe this was fixed since then: https://github.com/lbryio/lbry-desktop/issues/5681

I also think it should be fairly easy to force LBRY to be tunneled through Tor using OnionCat, without any specific programming. But we need to wait until someone tries to know for sure.

**Comment by Etile0** [comment]
I, personally, am against odysee because of Google. Odysee openly admits to using AdSense and Google Analytics (proof shown below using wappalyzer)
![Screenshot_20210709-195956_Bromite](https://user-images.githubusercontent.com/58475290/125113107-df6a7180-e0f0-11eb-8475-68fd3cc4d8b2.png)

**Comment by lrq3000** [comment]
@thomaszarebczan Any plan to remove Google Analytics and Google AdSense from LBRY (or at least make them optional)? It seems a bit counterproductive since Odysee aims to be a concurrent to YouTube, another Google product...

**Comment by lrq3000** [comment]
@tzarebczan Any plan to remove Google Analytics and Google AdSense from LBRY (or at least make them optional)? It seems a bit counterproductive since Odysee aims to be a concurrent to YouTube, another Google product...

**Comment by tzarebczan** [comment]
Thanks for the poke! We used to use Google analytics on odysee.com and lbry.tv, but no longer do. It may still show on live streams but we're getting rid of that also. We use open source Mataomo now for analytics. 

There is still GA in the LBRY app but that will go away as well.

**Comment by lrq3000** [comment]
@tzarebczan Thank you very much for your reply! Do you have any approximate timeframe for the full removal of Google Analytics in the LBRY app? Also what about Google AdSense (I'm not sure what you are referring to with the acronym "GA", I just noticed it can apply to both Analytics and AdSense lol).
